import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Navbar/Navbar'
import { Providers } from './GlobalRedux/provider';
import 'bootstrap/dist/css/bootstrap.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inventory System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header></Header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
